### ISSUE TITLE
32bit process running in a 64bit environment can't access NVIDIA API

### ISSUE THREAD

**Issue by guidou44** [falahati/NvAPIWrapper#14]
Hi!

Followed the sample, but I get this error at NVIDIA.Initialize();

Stacktrace:

   at NvAPIWrapper.Native.Helpers.DelegateFactory.NvAPI_QueryInterface(UInt32 interfaceId)
   at NvAPIWrapper.Native.Helpers.DelegateFactory.GetDelegate[T]()
   at NvAPIWrapper.Native.GeneralApi.Initialize()
   at NvAPIWrapper.NVIDIA.Initialize()

Any idea?

Thanks

**Comment by lekmagician** [comment]
I'm getting the same error when I called 'Display.GetDisplays()', changing my platform to x86, the problem still happened

**Comment by falahati** [comment]
NVAPI is only available to 64bit programs in a 64bit environment and to 32bit programs in a 32bit environment. so just compile and run the application in `Any CPU` mode and you should be ok.
