### ISSUE TITLE
How to set custom resolution?

### ISSUE THREAD

**Issue by MACTEP434** [falahati/NvAPIWrapper#53]
Hi! This part of code doesn't work

`var displayTest = new DisplayDevice(2147881091); `          
`var timing = displayTest.CalculateTiming(800, 600, 60, false);`
`var res1 = new CustomResolution(800, 600, NvAPIWrapper.Native.Display.ColorFormat.P8, timing);`
`displayTest.TrialCustomResolution(res1);`
`displayTest.SaveCustomResolution();`

Crashed on TrialCustomResolution (NvAPI error).
Help please

**Comment by falahati** [comment]
usually, it's a timing problem. Change the color format to `A8R8G8B8` and try again; otherwise, play with other variables; get the current timing and compare it with the one you have to see if you have to copy something over.

**Comment by MACTEP434** [comment]
> usually, it's a timing problem. Change the color format to `A8R8G8B8` and try again; otherwise, play with other variables; get the current timing and compare it with the one you have to see if you have to copy something over.

Maybe my `var displayTest = new DisplayDevice(2147881091);` - is single display? 
Im trying to set custom resolution before bulid mosiac.

Stacktrace:
`at NvAPIWrapper.Native.DisplayApi.TryCustomDisplay(IDictionary```2 displayIdCustomDisplayPairs)`
`at CrodMosaic.NET.Program.Main(String[] args) in C:\CobraDev\NvAPI\CrodMosaic.NET\CrodMosaic.NET\Program.cs:line 32`

**Comment by falahati** [comment]
these files might be useful as an example for grid management (mosaic v2) set of APIs:
https://github.com/falahati/HeliosDisplayManagement/tree/master/HeliosDisplayManagement.Shared/NVIDIA

otherwise, I have no new input here; the driver can reject a timing for absolutely any reason and NVAPI is not great with error messages. so my guess is the same as before.

    Maybe my `var displayTest = new DisplayDevice(2147881091);` - is single display?

`DisplayDevice` represents a single physical display device. I don't like the fact that you are using a const for the id, would rather see a code to get all display devices and find the right one. but yeah if the number is correct, it is a display device. also, I don't think you add a custom resolution while in the surround mode.

**Comment by falahati** [comment]
There is six types of display in NVAPI:

1. `DisplayDevice`: Represents a physical display, your own monitor
2. `Display`: A logical connected display 
3. `UnattachedDisplay`: A logical disconnected display 
2. `GridTopologyDisplay`: A physical display used in the mosaic arrangement
4. `PathTargetInfo`: A logical display device presented to windows (could be a physical device or Nvidia Surround virtual device)
3. `PathInfo`: A logical screen created by windows (contains one or more `PathTargetInfo` that contains one `Display`)

**Comment by MACTEP434** [comment]
I need a beer on this weekend, and try again.....

**Comment by coccoalberto97** [comment]
Hello, I'm also facing issues setting a custom resolution using this library.

`            
var displays = Display.GetDisplays();
foreach (var display in displays)
{
DisplayDevice displayTest = display.DisplayDevice;
var timing = displayTest.CalculateTiming(1920, 1080, 60, false);
var res1 = new CustomResolution(1920, 1080, NvAPIWrapper.Native.Display.ColorFormat.A8R8G8B8, timing);
try{
displayTest.TrialCustomResolution(res1);
displayTest.SaveCustomResolution();
.LogInformation(display.Name);
}catch(Exception e){
_logger.LogError(e, "Error");
}
}
`

Error NVAPI_ERROR:
   at NvAPIWrapper.Native.DisplayApi.TryCustomDisplay(IDictionary`2 displayIdCustomDisplayPairs)
   at NvAPIWrapper.Display.DisplayDevice.TrialCustomResolution(CustomResolution customResolution, UInt32[] displayIds, Boolean hardwareModeSetOnly)
   at NvAPIWrapper.Display.DisplayDevice.TrialCustomResolution(CustomResolution customResolution, Boolean hardwareModeSetOnly)

**Comment by FoLLgoTT** [comment]
I got the same problem. But when I use the overload with refreshRate of CustomResolution() it works. With ColorFormat I never got it to work.

**Comment by honoyang** [comment]
> I got the same problem. But when I use the overload with refreshRate of CustomResolution() it works. With ColorFormat I never got it to work.

I also got the same problem,

```
Timing timing = 
public Timing(ushort horizontalVisible, ushort verticalVisible, ushort horizontalBorder, ushort verticalBorder, ushort horizontalFrontPorch, ushort verticalFrontPorch, ushort horizontalSyncWidth, ushort verticalSyncWidth, ushort horizontalTotal, ushort verticalTotal, TimingHorizontalSyncPolarity horizontalPolarity, TimingVerticalSyncPolarity verticalPolarity, TimingScanMode scanMode, double refreshRateFrequencyInHz, ushort horizontalPixelRepetition = 1)

and call

CustomResolution res = new CustomResolution();
```

Error NVAPI_ERROR:
at NvAPIWrapper.Native.DisplayApi.TryCustomDisplay(IDictionary`2 displayIdCustomDisplayPairs)

@FoLLgoTT  could you help to show the workaround to avoid this problem? thanks!

for now, all the param is the same, only adjust refreshrate:
1. 60Hz: work
2. 48Hz: work
3. 61Hz: fail
4. 59 Hz: fail
5. 62 Hz: fail

is the calculation of refreshrate to _PixelClockIn10KHertz might be error?
I will try again when next week
